### ISSUE TITLE
Adding a user does not work

### ISSUE THREAD

**Issue by ennoausberlin** [Pier-CMS/Pier3#17]
![Screenshot 2021-05-06 at 18 26 52](https://user-images.githubusercontent.com/16412440/117333193-f8f50000-ae98-11eb-81a6-6d6b5b547daf.png)

I could not find an easier way to add users so I tried to add an existing component that can add users. But an DNU was generated. How do I add users?

**Comment by jborden23** [comment]
As a work-around (based on: PRWysiwygEditorExample>>#generateSiteMapSelect:) this adds a user, but they still can not be edited in the PUUsersWidget:

`PRKernel instances size = 1 ifTrue: [ PRKernel instances anyOne users add: ((PUUser named: 'jborden23') password: 'changeThis'; yourself) ].`

**Comment by ennoausberlin** [comment]
I can add users that way 👍

**Comment by jborden23** [comment]
Pull #18 should resolve this, be sure to clear any caches before loading the code.

**Comment by jborden23** [comment]
Tested successfully in a new Pier image.
